version: "3.9"
services:
    django:
        build: ./django
        expose:
            - "8000"
        environment:
            - DEBUG=1
        volumes:
            - ./django:/app
        command: python manage.py runserver 0.0.0.0:8000

    nuxt:
        build: ./nuxt-inline
        expose:
            - "3000"
        environment:
            - NODE_ENV=development
        volumes:
            - ./nuxt-inline:/app
            - /app/node_modules
        command: npx nuxi dev --port 3000 --host 0.0.0.0

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./django/app/static:/static:ro
        depends_on:
            - django
            - nuxt