name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Build Nuxt
        run: |
          cd nuxt-inline
          npm i && nuxi generate
          mv ./output/public/ ../django/app/static/nuxt-inline/
